import json
import os
from datetime import datetime

# List of all jpg files
files = [
"3 loups a l'eclipse.jpg",
"africaner.jpg",
"all you need is love 55x46  7.4.2025.jpg",
"Alpage de haute montagne.jpg",
"Anti covid religieux.jpg",
"arbre à rubans.jpg",
"assise sur un tabouret 80x60.jpg",
"Au petit matin.jpg",
"Aube en Moevan.jpg",
"Baignade dans la baie d'halong.jpg",
"Baigneuse asiatique.jpg",
"Barbe blanche.jpg",
"BB.jpg",
"Belle au chapeau de paille.jpg",
"blonde assise sur  un tabouret 55x46 17.4.2025.jpg",
"blonde atlètique 55x46  23.1.2025.jpg",
"blonde au maillot mouillé 55x46.jpg",
"Blonde boudeuse.jpg",
"blonde des bois 55x46 24.4.2025.jpg",
"Blonde en combinaison.jpg",
"blonde en petite culotte 55x46 30.1.2025.jpg",
"blonde en robe de plage 55x46 1.3.2025.jpg",
"blonde forte poitrine 55x46 8.2.2025.jpg",
"Bris de verre.jpg",
"Brumes japonnaises.jpg",
"Capuche et lunette rondes.jpg",
"Casse croute au blanc.jpg",
"Cerf de l'aube.jpg",
"Cerisier en fleurs.jpg",
"Chalut dans la tempete.jpg",
"Chalut à la derive.jpg",
"Chapeau noir.jpg",
"Chateau en Ecosse.jpg",
"Chene gehein.jpg",
"Cheveux fous.jpg",
"Chignon noir.jpg",
"Chouette.jpg",
"Corsage délacé.jpg",
"Création du temps.jpg",
"Curieuse.jpg",
"Dalias fanés.jpg",
"Dame blanche et chat vert.jpg",
"Délire hétylique.jpg",
"Enfants des étoiles.jpg",
"Falaise de 3 pieds.jpg",
"Famille goupil.jpg",
"Femme au beret.jpg",
"Femme au chapeau de toile.jpg",
"Femme au chapeau noir.jpg",
"Femme au costume marron.jpg",
"Femme en smoquing.jpg",
"Femme oeuf.jpg",
"Femme pressée.jpg",
"Femme voilage.jpg",
"Femme voilée.jpg",
"Femme volontaire.jpg",
"Femme à l'envers.jpg",
"Femme à la natte.jpg",
"Gina.jpg",
"Gourmande.jpg",
"Hendrix.jpg",
"Homme a capuche.jpg",
"Jardiniere.jpg",
"Jeune fille triste.jpg",
"Joueuse de baise-ball.jpg",
"Julie la rousse.jpg",
"Keith Richard.jpg",
"L'afgan.jpg",
"L'africaine aux yeux verts.jpg",
"L'asiatique.jpg",
"L'irlandaise.jpg",
"L'oeil du cyclone.jpg",
"L'oiselleuse.jpg",
"La balancoire.jpg",
"La bonne gagneuse.jpg",
"La brune.jpg",
"La dame de pérouge.jpg",
"La deculotté.jpg",
"La fille du plat pays.jpg",
"La garconne.jpg",
"La gitane.jpg",
"La lectrice.jpg",
"La lionne.jpg",
"La pianiste nu.jpg",
"La sauvageone.jpg",
"La tour infernale.jpg",
"Le choix dans la date.jpg",
"Le clop.jpg",
"Le corbeau d'Odin.jpg",
"Le livre des races.jpg",
"Le prana.jpg",
"Le souffle.jpg",
"Les doors.jpg",
"Levres gourmandes.jpg",
"Levé du soleil sur une goelette.jpg",
"Lion électrique.jpg",
"Légumes de la peur.jpg",
"Ma génese.jpg",
"Maquillage.jpg",
"Marilyne.jpg",
"Marine.jpg",
"Martin pecheur.jpg",
"Mick Jeager.jpg",
"Nature morte au citron vert.jpg",
"Nature morte à la tomate.jpg",
"Nu allongé de dos.jpg",
"Nu au bord de l'eau.jpg",
"Nu chapeau noir.jpg",
"Nu dans l'escalier.jpg",
"Nu sanguine.jpg",
"Nu sur la plage.jpg",
"Nymphe au maillot troué.jpg",
"Nymphe aux gros tetons.jpg",
"Oeuf à l'oeil.jpg",
"Ombres et lumières.jpg",
"Pensées sataniques.jpg",
"Poitrine imposante.jpg",
"Portait à la meche blonde.jpg",
"Portrait au voil blanc.jpg",
"Portrait au voil bleu.jpg",
"Portrait aux levres jaunes.jpg",
"Portrait bleu.jpg",
"Portrait encapuchonné.jpg",
"Portrait femme verte.jpg",
"Prairie en hiver.jpg",
"Prise de tete.jpg",
"Profil.jpg",
"Promenade dans la rue.jpg",
"Qui qui ma fille.jpg",
"Regarde par la fenetre.jpg",
"Relais de chasse.jpg",
"Robe bleue a bretelles.jpg",
"Robe grise a capuche.jpg",
"Robe transparente.jpg",
"Rousse aux yeux bleus.jpg",
"sans titre.jpg",
"Sausissonade.jpg",
"Seul sur son banc.jpg",
"Sorti de bain.jpg",
"Sous la pluie.jpg",
"Syndrome reptilien.jpg",
"Taitienne.jpg",
"TEST.jpg",
"Ukraine - Copie.jpg",
"Ukraine.jpg",
"Un long moment de solitude.jpg",
"Un éléphant sur une branche ca n'existe pas.jpg",
"Vestiges.jpg",
"Visage.jpg",
"Vision des 2 guides.jpg",
"Voilier à l'amarage.jpg"
]

def get_collection(name):
    name_lower = name.lower()
    if any(word in name_lower for word in ['paysage', 'montagne', 'aube', 'prairie', 'chateau', 'relais', 'ukraine', 'cerisier', 'arbre', 'brumes', 'ombres', 'alpage', 'chene', 'dame blanche', 'falaise', 'brumes japonnaises', 'chateau en ecosse', 'cerisier en fleurs', 'arbre à rubans', 'aube en moevan', 'dame blanche et chat vert', 'prairie en hiver', 'relais de chasse', 'ukraine', 'ombres et lumières']):
        return "Paysages"
    elif any(word in name_lower for word in ['animal', 'loup', 'chouette', 'cerf', 'famille goupil', 'lion', 'martin pecheur', 'oiseau', '3 loups', 'cerf de l\'aube', 'famille goupil', 'lion électrique', 'martin pecheur.jpg']):
        return "Animaux"
    elif any(word in name_lower for word in ['navigation', 'chalut', 'marine', 'voilier', 'goelette', 'baie d\'halong', 'levé du soleil sur une goelette', 'chalut dans la tempete', 'chalut à la derive', 'marine', 'voilier à l\'amarage']):
        return "Navigation"
    elif any(word in name_lower for word in ['nature morte', 'citron', 'tomate', 'legumes', 'légumes de la peur', 'nature morte au citron vert', 'nature morte à la tomate']):
        return "Nature morte"
    elif any(word in name_lower for word in ['portrait', 'femme', 'homme', 'blonde', 'rousse', 'brune', 'nu', 'nymphe', 'gina', 'marilyne', 'hendrix', 'keith richard', 'mick jeager', 'barbe blanche', 'capuche', 'chapeau', 'chignon', 'corsage', 'curieuse', 'gourmande', 'jardiniere', 'jeune fille', 'joueuse', 'julie', 'l\'afgan', 'l\'africaine', 'l\'asiatique', 'l\'irlandaise', 'l\'oeil du cyclone', 'l\'oiselleuse', 'la balancoire', 'la bonne gagneuse', 'la brune', 'la dame de pérouge', 'la deculotté', 'la fille du plat pays', 'la garconne', 'la gitane', 'la lectrice', 'la lionne', 'la pianiste nu', 'la sauvageone', 'la tour infernale', 'le choix dans la date', 'le clop', 'le corbeau d\'odin', 'le livre des races', 'le prana', 'le souffle', 'les doors', 'levres gourmandes', 'ma génese', 'maquillage', 'marine', 'oeuf à l\'oeil', 'pensées sataniques', 'poitrine imposante', 'portait à la meche blonde', 'portrait au voil blanc', 'portrait au voil bleu', 'portrait aux levres jaunes', 'portrait bleu', 'portrait encapuchonné', 'portrait femme verte', 'prise de tete', 'profil', 'promenade dans la rue', 'qui qui ma fille', 'regarde par la fenetre', 'robe bleue a bretelles', 'robe grise a capuche', 'robe transparente', 'rousse aux yeux bleus', 'sans titre', 'sausissonade', 'seul sur son banc', 'sorti de bain', 'sous la pluie', 'syndrome reptilien', 'taitienne', 'un long moment de solitude', 'un éléphant sur une branche ca n\'existe pas', 'vestiges', 'visage', 'vision des 2 guides', 'anti covid religieux', 'au petit matin', 'baignade dans la baie d\'halong', 'baigneuse asiatique', 'bb', 'belle au chapeau de paille', 'blonde assise sur un tabouret', 'blonde atlètique', 'blonde au maillot mouillé', 'blonde boudeuse', 'blonde des bois', 'blonde en combinaison', 'blonde en petite culotte', 'blonde en robe de plage', 'blonde forte poitrine', 'bris de verre', 'capuche et lunette rondes', 'casse croute au blanc', 'cheveux fous', 'chignon noir', 'corsage délacé', 'création du temps', 'curieuse', 'dalias fanés', 'délire hétylique', 'enfants des étoiles', 'femme au beret', 'femme au chapeau de toile', 'femme au chapeau noir', 'femme au costume marron', 'femme en smoquing', 'femme oeuf', 'femme pressée', 'femme voilage', 'femme voilée', 'femme volontaire', 'femme à l\'envers', 'femme à la natte', 'homme a capuche', 'jardiniere', 'jeune fille triste', 'joueuse de baise-ball', 'julie la rousse', 'test']):
        return "Decouverts"
    else:
        return "Divers"

images = []
for f in files:
    title = f.replace('.jpg', '')
    collection = get_collection(f)
    images.append({
        "filename": f,
        "path": f"images/{f}",
        "title": "",
        "artist": "Patrick RAPPENEAU",
        "collection": collection,
        "creationDate": "2025-03-22T00:00:00.000Z"
    })

with open('data/images.json', 'w', encoding='utf-8') as outfile:
    json.dump(images, outfile, ensure_ascii=False, indent=2)